/* Personal workflow extensions; catalog remains a replaceable upstream snapshot. */
const personal={compare:new Set(),profiles:readLocal('vibe-projects-v1',[]),active:readLocal('vibe-active-project-v1','')};
const activeProject=()=>personal.profiles.find(p=>p.id===personal.active);
const persistProjects=()=>{localStorage.setItem('vibe-projects-v1',JSON.stringify(personal.profiles));localStorage.setItem('vibe-active-project-v1',JSON.stringify(personal.active))};
const originalCard=componentCard;
componentCard=c=>originalCard(c).replace('<div class="card-footer">',`<div class="compare-action"><button data-compare="${c.id}" aria-pressed="${personal.compare.has(c.id)}">${personal.compare.has(c.id)?'✓ 已加入对比':'＋ 加入对比'}</button></div><div class="card-footer">`);
const originalFiltered=filteredComponents;
filteredComponents=()=>{const list=originalFiltered();if(state.sort==='recent')list.sort((a,b)=>(state.recent.indexOf(a.id)<0?999:state.recent.indexOf(a.id))-(state.recent.indexOf(b.id)<0?999:state.recent.indexOf(b.id)));return list};
const originalRender=render;
render=()=>{const renders={dashboard:renderDashboard,components:renderComponents,skills:renderSkills,references:renderReferences,favorites:renderFavorites};(renders[state.view]||renderDashboard)();$('#favoriteCount').textContent=state.favorites.size;renderProjectSummary();renderCompareBar()};
const projectPanel=document.createElement('section');projectPanel.className='dashboard-panel';projectPanel.id='projectPanel';$('.dashboard-grid').append(projectPanel);
function renderProjectSummary(){const p=activeProject();projectPanel.innerHTML=`<header><div><p class="eyebrow">PROJECT CONTEXT</p><h2>当前项目</h2></div><button data-project-edit>管理项目</button></header><p class="panel-copy">${p?`${escapeHTML(p.name)} · ${escapeHTML(p.stack)} · ${escapeHTML(p.theme)}<br>${escapeHTML(p.constraints)}`:'保存技术栈与界面约束，复制提示词时自动带上项目背景。'}</p>`}
function projectEditor(){showDialog(`<div class="dialog-body"><h2>项目预设</h2><p class="panel-copy">预设会写入开工提示词。兼容性尚未逐项实测，因此不自动隐藏组件。</p><label class="field-label">选择项目<select id="projectChoice"><option value="">新建项目</option>${personal.profiles.map(p=>`<option value="${escapeHTML(p.id)}" ${p.id===personal.active?'selected':''}>${escapeHTML(p.name)}</option>`).join('')}</select></label><form id="projectForm"><label class="field-label">项目名称<input name="name" required maxlength="80"></label><label class="field-label">技术栈<select name="stack"><option>React + Vite</option><option>Next.js</option><option>其他（需适配 React 组件）</option></select></label><label class="field-label">主题<select name="theme"><option>跟随系统</option><option>浅色</option><option>深色</option></select></label><label class="field-label">约束与品牌规则<textarea name="constraints" maxlength="3000" placeholder="例如：Tailwind 4、品牌色 #165DFF、移动端优先、禁止 WebGL、减少装饰动画"></textarea></label><button class="primary-action" type="submit">保存并启用</button><button type="button" data-project-off>暂不使用预设</button></form></div>`);const fill=()=>{const p=personal.profiles.find(x=>x.id===$('#projectChoice').value);const f=$('#projectForm');f.elements.name.value=p?.name||'';f.elements.stack.value=p?.stack||'React + Vite';f.elements.theme.value=p?.theme||'跟随系统';f.elements.constraints.value=p?.constraints||''};fill();$('#projectChoice').onchange=fill;$('#projectForm').onsubmit=e=>{e.preventDefault();const f=e.target;const id=$('#projectChoice').value||`project-${Date.now()}`;const p={id,name:f.elements.name.value.trim(),stack:f.elements.stack.value,theme:f.elements.theme.value,constraints:f.elements.constraints.value.trim()};if(!p.name)return;personal.profiles=personal.profiles.filter(x=>x.id!==id).concat(p);personal.active=id;persistProjects();$('#detailDialog').close();renderProjectSummary();toast('项目已启用')}}
const compareBar=document.createElement('div');compareBar.id='compareBar';compareBar.className='compare-bar';document.body.append(compareBar);
function renderCompareBar(){compareBar.hidden=!personal.compare.size;compareBar.innerHTML=`<span>已选 ${personal.compare.size} / 4</span><button data-show-compare ${personal.compare.size<2?'disabled':''}>并排对比</button><button data-clear-compare>清空选择</button>`;$$('[data-compare]').forEach(b=>{b.textContent=personal.compare.has(b.dataset.compare)?'✓ 已加入对比':'＋ 加入对比';b.setAttribute('aria-pressed',String(personal.compare.has(b.dataset.compare)))})}
function showCompare(){const selected=[...personal.compare].map(id=>DATA.components.find(c=>c.id===id)).filter(Boolean);showDialog(`<div class="dialog-body"><h2>组件对比</h2><p class="panel-copy">来源信息可直接比较；性能与移动端行为仍需在你的项目中验证。</p><div class="comparison-grid">${selected.map(c=>`<article>${preview(c)}<h3>${escapeHTML(c.title)}<small>${escapeHTML(c.cnTitle)}</small></h3><dl><dt>来源 / 许可</dt><dd>${escapeHTML(c.source)} / ${escapeHTML(c.license)}</dd><dt>交互类型</dt><dd>${escapeHTML(c.type)}</dd><dt>风格</dt><dd>${c.styles.map(escapeHTML).join('、')}</dd><dt>依赖</dt><dd>${c.dependencies.map(escapeHTML).join('、')||'未记录'}</dd><dt>预览</dt><dd>${c.previewMotion?'已有真实动图':'真实静态图，动态待补充'}</dd><dt>性能 / 移动端 / 无障碍</dt><dd>未实测，请结合源码与项目验收</dd></dl><button data-open-component="${c.id}">查看与开工</button></article>`).join('')}</div></div>`)}
const originalOpen=openComponent;
openComponent=id=>{originalOpen(id);const c=DATA.components.find(c=>c.id===id),p=activeProject();const box=$('.prompt-box code');if(p){const prompt=`项目：${p.name}\n技术栈：${p.stack}\n主题：${p.theme}\n约束：${p.constraints||'遵循现有项目约定'}\n\n${box.textContent}`;box.textContent=prompt;$('.prompt-box [data-copy]').dataset.copy=encodeURIComponent(prompt)}
  const related=DATA.components.filter(x=>x.id!==id).map(x=>({x,score:(x.type===c.type?4:0)+x.styles.filter(s=>c.styles.includes(s)).length+(x.name===c.name?8:0)})).filter(x=>x.score>=4).sort((a,b)=>b.score-a.score).slice(0,4);
  const section=document.createElement('section');section.className='related';section.innerHTML=`<h3>相似组件 · 按类型与风格匹配</h3><div class="relation-list">${related.map(({x})=>{const common=x.styles.filter(s=>c.styles.includes(s));const why=x.name===c.name?'同名的不同来源实现':x.type===c.type?`同为「${x.type}」${common.length?`，共同风格：${common.join('、')}`:''}`:`共同风格：${common.join('、')}`;return`<button data-open-component="${x.id}">${escapeHTML(x.title)} · ${escapeHTML(x.cnTitle)}<small>${escapeHTML(why)}</small></button><button data-compare="${x.id}">＋ 对比</button>`}).join('')}</div><p class="panel-copy">“自动匹配”来自类型与风格标签，尚未逐项人工验证可替换性。</p><button data-compare="${c.id}">＋ 将当前组件加入对比</button>`;$('.dialog-body').append(section);
  const sourceSection=document.createElement('section');sourceSection.className='related';sourceSection.innerHTML='<h3>补充设计依据</h3><div class="relation-list">'+(window.VIBE_SUPPLEMENTS||[]).map(s=>`<button data-source="${s.id}">${escapeHTML(s.title)}</button>`).join('')+'</div><p class="panel-copy">行为与设计通用参考；原有参考文档为自动关联，尚未逐项人工精选。</p>';$('.dialog-body').append(sourceSection);bindDynamic();renderCompareBar()};
// A single click explicitly starts a motion preview; leaving hover does not alter it.
const oldBind=bindDynamic;
bindDynamic=()=>{oldBind();$$('img[data-motion]').forEach(img=>{const parent=img.closest('.real-preview');parent.querySelectorAll('.motion-toggle').forEach(b=>b.remove());parent.replaceWith(parent.cloneNode(true))});$$('.real-preview').forEach(parent=>{const img=parent.querySelector('img[data-motion]');if(!img)return;const b=document.createElement('button');b.className='motion-toggle';b.textContent='播放动图';b.onclick=()=>{const playing=b.getAttribute('aria-pressed')==='true';img.src=playing?img.dataset.static:img.dataset.motion;b.setAttribute('aria-pressed',String(!playing));b.textContent=playing?'播放动图':'停止播放'};parent.append(b)});$$('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(decodeURIComponent(b.dataset.copy));toast('已复制')}catch{toast('复制受限，请选中提示词手动复制')}})};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-project-edit'))projectEditor();if(b.hasAttribute('data-project-off')){personal.active='';persistProjects();$('#detailDialog').close();renderProjectSummary()}if(b.dataset.compare){const id=b.dataset.compare;if(personal.compare.has(id))personal.compare.delete(id);else if(personal.compare.size<4)personal.compare.add(id);else return toast('最多对比 4 个组件');renderCompareBar()}if(b.hasAttribute('data-clear-compare')){personal.compare.clear();renderCompareBar()}if(b.hasAttribute('data-show-compare'))showCompare();if(b.dataset.source)openSource(b.dataset.source)});
function openSource(id){const s=(window.VIBE_SUPPLEMENTS||[]).find(x=>x.id===id);if(!s)return;showDialog(`<div class="dialog-body"><h2>${escapeHTML(s.title)}</h2><p>${escapeHTML(s.description)}</p><p class="panel-copy">快照 ${s.checkedAt.slice(0,10)} · ${s.revision.slice(0,8)} · 已下载 ${s.documents.length} 篇。这里是资料快照，并非整个组件库已接入。</p>${s.documents.map(d=>`<details class="source-document"><summary>${escapeHTML(d.name)}</summary><pre class="source-text">${escapeHTML(d.content)}</pre><a href="${d.url}" target="_blank" rel="noopener">查看固定版本原文 ↗</a></details>`).join('')}</div>`)}
const sourcePanel=document.createElement('section');sourcePanel.className='dashboard-panel';sourcePanel.innerHTML='<header><div><p class="eyebrow">SUPPLEMENTAL SOURCES</p><h2>补充资料</h2></div></header><div class="compact-list">'+(window.VIBE_SUPPLEMENTS||[]).map(s=>`<button data-source="${s.id}"><b>${escapeHTML(s.title)}</b><span>${escapeHTML(s.role)}</span></button>`).join('')+'</div>';$('.dashboard-grid').append(sourcePanel);
$('#exportData').onclick=()=>{const data={version:2,exportedAt:new Date().toISOString(),favorites:[...state.favorites],recent:state.recent,notes:state.notes,used:state.used,profiles:personal.profiles,active:personal.active};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='vibe-handbook-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('备份已导出，请保存到 D 盘')};
$('#importData').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5e6)throw Error();const d=JSON.parse(await file.text());const record=x=>x&&typeof x==='object'&&!Array.isArray(x);if(![1,2].includes(d.version)||!Array.isArray(d.favorites)||!Array.isArray(d.recent)||!record(d.notes)||!record(d.used))throw Error();if(!d.favorites.every(x=>typeof x==='string')||!d.recent.every(x=>typeof x==='string')||!Object.values(d.notes).every(x=>typeof x==='string')||!Object.values(d.used).every(x=>Array.isArray(x)&&x.every(v=>typeof v==='string')))throw Error();if(d.profiles&&(!Array.isArray(d.profiles)||!d.profiles.every(p=>record(p)&&['id','name','stack','theme','constraints'].every(k=>typeof p[k]==='string'))))throw Error();state.favorites=new Set([...state.favorites,...d.favorites.filter(findAny)]);state.recent=[...new Set([...state.recent,...d.recent])].filter(id=>DATA.components.some(c=>c.id===id)).slice(0,20);for(const [id,note] of Object.entries(d.notes)){if(!DATA.components.some(c=>c.id===id))continue;state.notes[id]=state.notes[id]&&state.notes[id]!==note?state.notes[id]+'\n\n[导入笔记]\n'+note:note}for(const [id,projects] of Object.entries(d.used))if(DATA.components.some(c=>c.id===id))state.used[id]=[...new Set([...(state.used[id]||[]),...projects])];for(const p of d.profiles||[])if(!personal.profiles.some(x=>x.id===p.id))personal.profiles.push(p);for(const [key,value] of [['vibe-favorites-v2',[...state.favorites]],['vibe-recent-v1',state.recent],['vibe-notes-v1',state.notes],['vibe-used-v1',state.used]])localStorage.setItem(key,JSON.stringify(value));persistProjects();render();toast('已合并备份，保留现有笔记')}catch{toast('导入失败：请使用有效的手册备份 JSON')}finally{e.target.value=''}};
render();
