/* 分享版体验：完整备份、首次引导、版本信息和离线安装。 */
const HANDBOOK_VERSION='0.4.0',BACKUP_VERSION=3;
const SHARE_KEYS=['vibe-favorites-v2','vibe-recent-v1','vibe-notes-v1','vibe-used-v1','vibe-projects-v1','vibe-active-project-v1','vibe-my-components-v1','vibe-taxonomy-v3','vibe-taxonomy-operations-v1','vibe-component-taxonomy-assignments-v1','vibe-theme'];
const readShareValue=key=>{const raw=localStorage.getItem(key);if(raw===null)return null;try{return JSON.parse(raw)}catch{return raw}};
function fullBackup(){return{backupVersion:BACKUP_VERSION,appVersion:HANDBOOK_VERSION,exportedAt:new Date().toISOString(),origin:location.origin,data:Object.fromEntries(SHARE_KEYS.map(k=>[k,readShareValue(k)]).filter(([,v])=>v!==null))}}
function downloadBackup(){const url=URL.createObjectURL(new Blob([JSON.stringify(fullBackup(),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`vibe-index-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('完整备份已导出')}
function normalizeLegacy(d){if(d.backupVersion===3&&d.data)return d;const data={};if(d.favorites)data['vibe-favorites-v2']=d.favorites;if(d.recent)data['vibe-recent-v1']=d.recent;if(d.notes)data['vibe-notes-v1']=d.notes;if(d.used)data['vibe-used-v1']=d.used;if(d.profiles)data['vibe-projects-v1']=d.profiles;if(d.active!==undefined)data['vibe-active-project-v1']=d.active;return{backupVersion:d.version||1,data}}
function backupSummary(d){const x=d.data||{},components=x['vibe-my-components-v1']||[],notes=x['vibe-notes-v1']||{},favorites=x['vibe-favorites-v2']||[],tags=x['vibe-taxonomy-v3']?.groups?.tag||[];return`${components.length} 个个人组件 · ${tags.length} 个个人标签 · ${favorites.length} 个收藏 · ${Object.keys(notes).length} 篇笔记`}
function mergeValue(current,incoming){if(Array.isArray(current)&&Array.isArray(incoming))return[...current,...incoming].filter((v,i,a)=>a.findIndex(x=>JSON.stringify(x)===JSON.stringify(v))===i);if(current&&incoming&&typeof current==='object'&&typeof incoming==='object')return{...current,...incoming};return incoming}
function applyBackup(data,mode){for(const [key,value] of Object.entries(data)){if(!SHARE_KEYS.includes(key))continue;const next=mode==='merge'?mergeValue(readShareValue(key),value):value;localStorage.setItem(key,typeof next==='string'?next:JSON.stringify(next))}localStorage.setItem('vibe-onboarding-seen','true');location.reload()}
function previewImport(d){showDialog(`<div class="dialog-body import-preview"><p class="eyebrow">BACKUP ${escapeHTML(String(d.backupVersion))}</p><h2>导入前检查</h2><p class="dialog-summary">${escapeHTML(backupSummary(d))}</p><div class="decision-callout"><b>请选择导入方式</b><p>合并会保留当前资料；完全覆盖会用备份替换当前手册数据。</p></div><div class="dialog-actions"><button data-import-mode="merge">合并到当前资料</button><button class="danger-action" data-import-mode="replace">完全覆盖</button></div></div>`);$$('[data-import-mode]').forEach(b=>b.onclick=()=>{if(b.dataset.importMode==='replace'&&b.dataset.armed!=='true'){b.dataset.armed='true';b.textContent='再次点击确认覆盖';return}applyBackup(d.data,b.dataset.importMode)})}
$('#exportData').onclick=downloadBackup;
$('#importData').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>25e6)throw Error('文件超过 25MB');const d=normalizeLegacy(JSON.parse(await f.text()));if(!d.data||typeof d.data!=='object')throw Error('格式错误');previewImport(d)}catch(err){toast(`导入失败：${err.message||'备份无效'}`)}finally{e.target.value=''}};
function onboarding(){if(localStorage.getItem('vibe-onboarding-seen'))return;showDialog(`<div class="dialog-body onboarding"><p class="eyebrow">WELCOME TO VIBE/INDEX</p><h2>三步找到合适的交互</h2><ol><li><b>用中文描述效果</b><span>例如“数字增长动画”或“卡片悬停有空间感”。</span></li><li><b>比较组件与依据</b><span>查看真实预览、相似组件和关联文档。</span></li><li><b>复制开工提示词</b><span>带着交互、无障碍和性能约束开始 Vibe Coding。</span></li></ol><div class="local-note">收藏、笔记、标签和个人组件只保存在当前浏览器。换设备前请导出备份。</div><div class="dialog-actions"><button data-onboard-example="卡片悬停有空间感">用示例开始</button><button class="primary-action" data-onboard-done>直接进入</button></div></div>`);$('[data-onboard-done]').onclick=()=>{localStorage.setItem('vibe-onboarding-seen','true');$('#detailDialog').close()};$('[data-onboard-example]').onclick=e=>{localStorage.setItem('vibe-onboarding-seen','true');$('#detailDialog').close();$('#searchInput').value=e.target.dataset.onboardExample;state.query=e.target.dataset.onboardExample;switchView('components')}}
const footer=document.querySelector('footer');footer?.insertAdjacentHTML('beforeend',`<p class="version-note">V${HANDBOOK_VERSION} · 组件数据 2026-09-08 · <span>个人修改仅当前浏览器可见</span></p>`);
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
setTimeout(onboarding,80);
