/* 分层标签系统：一级目录稳定，二级标签可管理；所有变更级联到组件与筛选器。 */
const TAGS_KEY='vibe-tag-library-v1',TAXONOMY_KEY='vibe-taxonomy-v3',TAXONOMY_OPS_KEY='vibe-taxonomy-operations-v1',COMPONENT_TAGS_KEY='vibe-component-taxonomy-assignments-v1';
const readTagJson=(v,f)=>{try{return JSON.parse(v)??f}catch{return f}},tagSort=a=>[...new Set(a.filter(Boolean))].sort((x,y)=>x.localeCompare(y,'zh-CN'));
const GROUP_DEFS=[
  {id:'type',label:'交互类型',field:'type',stateKey:'type',filter:'#typeFilters',multiple:false},
  {id:'style',label:'风格特征',field:'styles',stateKey:'style',filter:'#styleFilters',multiple:true},
  {id:'tag',label:'个人标签',field:'tags',stateKey:'tag',filter:'#tagFilters',multiple:true}
];
const OFFICIAL_COMPONENT_TAGS=Object.fromEntries((window.VIBE_DATA?.components||[]).map(c=>[c.id,{type:c.type,styles:[...(c.styles||[])],tags:[...(c.tags||[])]}]));
function valuesFor(id,components=window.VIBE_DATA?.components||[]){const d=GROUP_DEFS.find(x=>x.id===id);return tagSort(components.flatMap(c=>Array.isArray(c[d.field])?c[d.field]:[c[d.field]]))}
function initialTaxonomy(){const old=readTagJson(localStorage.getItem(TAGS_KEY),[]),type=valuesFor('type'),style=valuesFor('style'),used=valuesFor('tag');return{version:3,groups:{type,style,tag:tagSort([...used,...old.filter(x=>!type.includes(x)&&!style.includes(x))])}}}
function readTaxonomy(){const s=readTagJson(localStorage.getItem(TAXONOMY_KEY),null);if(s?.version===3&&s.groups)return s;const n=initialTaxonomy();localStorage.setItem(TAXONOMY_KEY,JSON.stringify(n));return n}
const Tags={taxonomy:readTaxonomy(),get groups(){return GROUP_DEFS.map(d=>({...d,items:this.taxonomy.groups[d.id]||[]}))},get library(){return this.taxonomy.groups.tag||[]},set library(v){this.taxonomy.groups.tag=tagSort(v);this.save()},save(){localStorage.setItem(TAXONOMY_KEY,JSON.stringify(this.taxonomy))},reload(){this.taxonomy=readTaxonomy()},applyOverridesToData};
const operations=()=>readTagJson(localStorage.getItem(TAXONOMY_OPS_KEY),[]),writeOperations=v=>localStorage.setItem(TAXONOMY_OPS_KEY,JSON.stringify(v));
const componentAssignments=()=>readTagJson(localStorage.getItem(COMPONENT_TAGS_KEY),{}),writeComponentAssignments=v=>localStorage.setItem(COMPONENT_TAGS_KEY,JSON.stringify(v));
function mutateComponent(c,id,from,to){const d=GROUP_DEFS.find(x=>x.id===id);if(!d||!c)return false;if(d.multiple){const before=Array.isArray(c[d.field])?c[d.field]:[],after=tagSort(before.flatMap(v=>v===from?(to?[to]:[]):[v]));if(before.join('\u0001')===after.join('\u0001'))return false;c[d.field]=after;return true}if(c[d.field]!==from)return false;c[d.field]=to||'未分类';return true}
function applyOverridesToData(){for(const op of operations())for(const c of(window.VIBE_DATA?.components||[]))mutateComponent(c,op.group,op.from,op.to)}
function syncSelected(id,from,to){const d=GROUP_DEFS.find(x=>x.id===id),s=d&&typeof state!=='undefined'?state[d.stateKey]:null;if(s?.has(from)){s.delete(from);if(to)s.add(to)}}
function applyChange(id,from,to){for(const c of(window.VIBE_DATA?.components||[]))mutateComponent(c,id,from,to);const pc=window.PersonalComponents;if(pc){let changed=false;for(const c of pc.list)changed=mutateComponent(c,id,from,to)||changed;if(changed)pc.save()}const saved=componentAssignments();for(const entry of Object.values(saved))mutateComponent(entry,id,from,to);writeComponentAssignments(saved);writeOperations([...operations(),{group:id,from,to:to||null}]);syncSelected(id,from,to)}
function addTag(name,id='tag'){const v=String(name||'').trim().slice(0,24),a=Tags.taxonomy.groups[id];if(!v||!a||a.includes(v))return false;a.push(v);Tags.taxonomy.groups[id]=tagSort(a);Tags.save();refreshAllTaxonomyFilters();return true}
function renameTag(oldName,newName,id='tag'){const o=String(oldName||'').trim(),n=String(newName||'').trim().slice(0,24),a=Tags.taxonomy.groups[id];if(!o||!n||o===n||!a?.includes(o))return false;Tags.taxonomy.groups[id]=tagSort(a.flatMap(v=>v===o?(a.includes(n)?[]:[n]):[v]));Tags.save();applyChange(id,o,n);refreshAllTaxonomyFilters();return true}
function removeTag(name,id='tag'){const v=String(name||'').trim(),a=Tags.taxonomy.groups[id];if(!a?.includes(v))return false;Tags.taxonomy.groups[id]=a.filter(x=>x!==v);if(id==='type'&&!Tags.taxonomy.groups.type.includes('未分类'))Tags.taxonomy.groups.type.push('未分类');Tags.taxonomy.groups[id]=tagSort(Tags.taxonomy.groups[id]);Tags.save();applyChange(id,v,null);refreshAllTaxonomyFilters();return true}
function bindFreshFilters(){document.querySelectorAll('[data-filter]').forEach(input=>{const s=typeof state!=='undefined'?state[input.dataset.filter]:null;input.checked=!!s?.has(input.value);input.onchange=e=>{const t=e.currentTarget,set=state[t.dataset.filter];t.checked?set.add(t.value):set.delete(t.value);render()}})}
function refreshAllTaxonomyFilters(){try{filters('type','#typeFilters');filters('styles','#styleFilters','style');filters('tags','#tagFilters','tag');bindFreshFilters();if(typeof render==='function')render()}catch{}}
function refreshTagFilters(){refreshAllTaxonomyFilters()}
function tagUsageCount(id='tag'){const counts={},d=GROUP_DEFS.find(x=>x.id===id);for(const c of(window.VIBE_DATA?.components||[])){const raw=c[d.field],a=Array.isArray(raw)?raw:[raw];for(const v of new Set(a.filter(Boolean)))counts[v]=(counts[v]||0)+1}return counts}

function applyComponentAssignments(){const saved=componentAssignments();for(const c of(window.VIBE_DATA?.components||[])){const entry=saved[c.id];if(!entry)continue;c.type=entry.type||c.type;c.styles=tagSort(entry.styles||[]);c.tags=tagSort(entry.tags||[])}}
function persistComponentTags(c){if(c.personal&&window.PersonalComponents){const local=PersonalComponents.byId(c.id);if(local){local.type=c.type;local.styles=c.styles;local.tags=c.tags;PersonalComponents.save()}}else{const saved=componentAssignments();saved[c.id]={type:c.type,styles:c.styles,tags:c.tags};writeComponentAssignments(saved)}}
function restoreComponentTags(id){const c=window.VIBE_DATA.components.find(x=>x.id===id),base=OFFICIAL_COMPONENT_TAGS[id];if(!c||!base)return;c.type=base.type;c.styles=[...base.styles];c.tags=[...base.tags];for(const op of operations())mutateComponent(c,op.group,op.from,op.to);const saved=componentAssignments();delete saved[id];writeComponentAssignments(saved);refreshAllTaxonomyFilters();openComponent(id);toast('已恢复此组件的官方分类')}
function quickAssignTag(id,name){const c=window.VIBE_DATA.components.find(x=>x.id===id),value=String(name||'').trim().slice(0,24);if(!c||!value)return;addTag(value,'tag');c.tags=tagSort([...(c.tags||[]),value]);persistComponentTags(c);refreshAllTaxonomyFilters();openComponent(id);toast(`已创建并添加「${value}」`)}
function taxonomyChoice(group,selected){return `<div class="component-tag-options" data-choice-group="${group.id}">${group.items.map(v=>`<label class="component-tag-choice"><input type="${group.multiple?'checkbox':'radio'}" name="component-${group.id}" value="${escapeHTML(v)}" ${selected.includes(v)?'checked':''}><span>${escapeHTML(v)}</span></label>`).join('')}</div>`}
function componentTagEditor(c){const type=Tags.groups.find(x=>x.id==='type'),style=Tags.groups.find(x=>x.id==='style'),tag=Tags.groups.find(x=>x.id==='tag');return `<section class="related component-tag-editor"><div class="component-tag-head"><div><h3>组件标签</h3><p class="panel-copy">只调整当前组件，不会删除标签库中的标签。</p></div><button class="link" data-open-taxonomy>管理标签库</button></div><div class="component-tag-group"><b>交互类型</b>${taxonomyChoice(type,[c.type])}</div><div class="component-tag-group"><b>风格特征</b>${taxonomyChoice(style,c.styles||[])}</div><div class="component-tag-group"><b>个人标签</b>${tag.items.length?taxonomyChoice(tag,c.tags||[]):'<p class="panel-copy">暂无个人标签，可直接在下方创建。</p>'}<div class="quick-tag-row"><input data-quick-tag maxlength="24" placeholder="新标签名称"><button data-quick-tag-add>创建并添加</button></div></div><div class="component-tag-actions">${OFFICIAL_COMPONENT_TAGS[c.id]?'<button class="link" data-restore-component>恢复官方分类</button>':''}<span data-tag-save-status></span><button class="primary-action" data-save-component-tags="${escapeHTML(c.id)}">保存组件标签</button></div></section>`}
function saveComponentTags(id,root){const c=window.VIBE_DATA.components.find(x=>x.id===id);if(!c)return;const checked=group=>[...root.querySelectorAll(`[data-choice-group="${group}"] input:checked`)].map(x=>x.value),next={type:checked('type')[0]||c.type,styles:checked('style'),tags:checked('tag')};c.type=next.type;c.styles=tagSort(next.styles);c.tags=tagSort(next.tags);persistComponentTags(c);refreshAllTaxonomyFilters();openComponent(id);toast('组件标签已保存并同步')}
const taxonomyOpenComponent=openComponent;
openComponent=id=>{taxonomyOpenComponent(id);const c=window.VIBE_DATA.components.find(x=>x.id===id),body=document.querySelector('#dialogContent .dialog-body');if(!c||!body)return;body.insertAdjacentHTML('beforeend',componentTagEditor(c));const editor=body.querySelector('.component-tag-editor');editor.querySelector('[data-save-component-tags]').onclick=()=>saveComponentTags(id,editor);editor.querySelector('[data-open-taxonomy]').onclick=()=>openTagsManager();editor.querySelector('[data-restore-component]')?.addEventListener('click',()=>restoreComponentTags(id));const quick=editor.querySelector('[data-quick-tag]'),quickAdd=editor.querySelector('[data-quick-tag-add]');quickAdd.onclick=()=>quickAssignTag(id,quick.value);quick.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();quickAdd.click()}}};
function renderTagsInput(selected=[]){const lib=Tags.library,sel=[...new Set(selected)];return `<div class="tags-input"><div class="tag-chips">${sel.map(t=>`<span class="tag-chip">${escapeHTML(t)}<button type="button" data-untag="${escapeHTML(t)}" aria-label="移除">×</button></span>`).join('')}</div><input id="tagInput" list="tagDatalist" placeholder="从个人标签选择或输入新标签，回车添加" maxlength="24" autocomplete="off"><datalist id="tagDatalist">${lib.map(t=>`<option value="${escapeHTML(t)}">`).join('')}</datalist><p class="panel-copy">个人标签：${lib.length?lib.map(t=>`<button type="button" class="tag-suggestion" data-tag-add="${escapeHTML(t)}">${escapeHTML(t)}</button>`).join(''):'（暂无，可直接输入）'}</p></div>`}
Tags.renderTagsInput=renderTagsInput;
function groupTreeCard(g,i){const counts=tagUsageCount(g.id),uses=Object.values(counts).reduce((a,b)=>a+b,0);return `<details class="taxonomy-card" ${i===0?'open':''} data-group-card="${g.id}"><summary><span class="tree-caret">›</span><span class="tree-folder">▱</span><span><b>${g.label}</b><small>一级标签 · ${g.items.length} 个二级标签</small></span><em>${uses} 次使用</em></summary><div class="tree-branch"><div class="tag-add-row"><input data-new-for="${g.id}" maxlength="24" placeholder="新增二级标签"><button class="primary-action" data-add-for="${g.id}">添加</button></div>${g.items.length?`<ul class="tag-manage">${g.items.map(t=>`<li class="tag-row"><span class="tree-leaf"></span><span class="tag-label">${escapeHTML(t)}</span><small>${counts[t]||0} 个组件</small><button class="link" data-rename="${escapeHTML(t)}" data-group="${g.id}">改名</button><button class="link danger" data-del="${escapeHTML(t)}" data-group="${g.id}">删除</button></li>`).join('')}</ul>`:'<p class="tree-empty">这个目录还没有二级标签。</p>'}</div></details>`}
function openTagsManager(focusGroup){if(typeof showDialog!=='function')return;showDialog(`<div class="dialog-body taxonomy-dialog"><p class="eyebrow">COMPONENT TAXONOMY</p><h2>组件标签树</h2><p class="panel-copy">一级标签用于固定分类，二级标签可增删改。修改会立即同步到组件卡片、详情页和左侧筛选列表，并在刷新后保留。</p><div class="taxonomy-tree">${Tags.groups.map((g,i)=>groupTreeCard(g,focusGroup?g.id===focusGroup?0:1:i)).join('')}</div></div>`);if(focusGroup)document.querySelector(`[data-group-card="${focusGroup}"]`)?.setAttribute('open','');document.querySelectorAll('[data-add-for]').forEach(b=>b.onclick=()=>{const id=b.dataset.addFor,input=document.querySelector(`[data-new-for="${id}"]`),v=input.value.trim();if(!v)return;if(!addTag(v,id))return toast('标签已存在或名称无效');openTagsManager(id);toast(`已添加「${v}」`)});document.querySelectorAll('[data-new-for]').forEach(i=>i.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();document.querySelector(`[data-add-for="${i.dataset.newFor}"]`)?.click()}});document.querySelectorAll('[data-rename]').forEach(b=>b.onclick=()=>{const n=prompt(`把「${b.dataset.rename}」改名为：`,b.dataset.rename);if(!n?.trim()||n.trim()===b.dataset.rename)return;if(!renameTag(b.dataset.rename,n.trim(),b.dataset.group))return toast('改名失败');openTagsManager(b.dataset.group);toast('名称、组件与筛选器已同步')});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{const label=GROUP_DEFS.find(x=>x.id===b.dataset.group)?.label;if(!confirm(`删除${label}「${b.dataset.del}」？组件上的对应分类也会同步移除。`))return;removeTag(b.dataset.del,b.dataset.group);openTagsManager(b.dataset.group);toast('标签及组件引用已删除')})}
/* 覆盖旧版 prompt/confirm 管理器：内联编辑更适合内置浏览器，也避免弹窗阻断。 */
function openTagsManager(focusGroup){
  if(typeof showDialog!=='function')return;
  showDialog(`<div class="dialog-body taxonomy-dialog"><p class="eyebrow">COMPONENT TAXONOMY</p><h2>组件标签树</h2><p class="panel-copy">一级标签用于固定分类，二级标签可增删改。修改会立即同步到组件卡片、详情页和左侧筛选列表，并在刷新后保留。</p><div class="taxonomy-tree">${Tags.groups.map((g,i)=>groupTreeCard(g,focusGroup?g.id===focusGroup?0:1:i)).join('')}</div></div>`);
  if(focusGroup)document.querySelector(`[data-group-card="${focusGroup}"]`)?.setAttribute('open','');
  document.querySelectorAll('[data-add-for]').forEach(button=>button.onclick=()=>{const group=button.dataset.addFor,input=document.querySelector(`[data-new-for="${group}"]`),value=input.value.trim();if(!value)return;if(!addTag(value,group))return toast('标签已存在或名称无效');openTagsManager(group);toast(`已添加「${value}」`)});
  document.querySelectorAll('[data-new-for]').forEach(input=>input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();document.querySelector(`[data-add-for="${input.dataset.newFor}"]`)?.click()}});
  document.querySelectorAll('[data-rename]').forEach(button=>button.onclick=()=>{
    const row=button.closest('.tag-row'),label=row.querySelector('.tag-label'),oldName=button.dataset.rename,group=button.dataset.group;
    label.outerHTML=`<input class="tag-inline-edit" value="${escapeHTML(oldName)}" maxlength="24" aria-label="编辑标签名称">`;
    const input=row.querySelector('.tag-inline-edit');button.textContent='保存';row.querySelector('[data-del]').textContent='取消';input.focus();input.select();
    const save=()=>{const next=input.value.trim();if(!next||next===oldName)return openTagsManager(group);if(!renameTag(oldName,next,group))return toast('改名失败：名称可能已存在');openTagsManager(group);toast('名称、组件与筛选器已同步')};
    button.onclick=save;input.onkeydown=e=>{if(e.key==='Enter')save();if(e.key==='Escape')openTagsManager(group)};row.querySelector('[data-del]').onclick=()=>openTagsManager(group);
  });
  document.querySelectorAll('[data-del]').forEach(button=>button.onclick=()=>{
    if(button.dataset.armed!=='true'){button.dataset.armed='true';button.textContent='确认删除';button.classList.add('is-armed');setTimeout(()=>{if(button.isConnected){button.dataset.armed='false';button.textContent='删除';button.classList.remove('is-armed')}},3000);return}
    removeTag(button.dataset.del,button.dataset.group);openTagsManager(button.dataset.group);toast('标签及组件引用已删除');
  });
}

applyComponentAssignments();
applyOverridesToData();
refreshAllTaxonomyFilters();
